sudo: false

language:
  - cpp

services:
  - docker

script:
  - ./travis.sh

env:
  matrix:
    - OS=el DIST=6 PACK=rpm
    - OS=el DIST=7 PACK=rpm
    - OS=fedora DIST=23 PACK=rpm
    - OS=fedora DIST=24 PACK=rpm
    - OS=fedora DIST=25 PACK=rpm
    - OS=ubuntu DIST=trusty PACK=deb
    - OS=ubuntu DIST=precise PACK=deb
    - OS=ubuntu DIST=xenial PACK=deb
    - OS=ubuntu DIST=yakkety PACK=deb
    - OS=debian DIST=jessie PACK=deb
    - OS=debian DIST=wheezy PACK=deb
    - OS=debian DIST=stretch PACK=deb

notifications:
  email: false
  irc: false

