sudo: false

services:
  - docker

script:
  - ./test.sh

env:
  matrix:
    - OS=el DIST=7 PACK=rpm PLATFORM='GCC.sh --without-debug --without-flat-makefile --without-ncbi-c'
    - OS=ubuntu DIST=trusty PACK=deb PLATFORM='GCC.sh --without-debug --without-flat-makefile --without-ncbi-c'

notifications:
  email: false
  irc: false

